### ISSUE TITLE
Propose move to gerrithub workflow

### ISSUE THREAD

**Issue by aakarshg** [jtaleric/benchmark-operator#23]
Github workflow has the following issues:

- Working on other users PR has been significantly difficult leading to PR cycle
- Another major issue is the need for squashing commits.
- There is no real way to look for differences between commits if they were squashed or amended.

I propose that we move to Gerrithub workflow as it addresses above mentioned problem and also provides additional benefits such as

- Neat UI to facilitate voting on patchsets/reviews submitted.
- Better integration with Jenkins. 
- Even possible to run jobs that get triggered only on merge. This would be crucial in building operator images and pushing to quay.

The only backdrop I see is that some of us will be needing to adopt to new workflow.

**Comment by jtaleric** [comment]
@aakarshg Most openshift / kube projects use the github workflow. 

Agree:
- working on PR's isn't straight forward
- squashing can happen prior to merge
- Agreed... 

I worry about the migration and what that does to contributions. We are familiar with gerrithub, so that is why we naturally want to go towards it.

**Comment by jtaleric** [comment]
Closing this issue, as we have spoken about this... Re-open if you think this isn't resolved.
